### ISSUE TITLE
Registration requests for already existing users should fail with a 4xx error 

### ISSUE THREAD

**Issue by mjs** [TheCacophonyProject/cacophony-api#19]
Currently they fail with a 5xx.

**Comment by jamie-sherriff** [comment]
@mjs Was scanning over good first issues and i had a quick look at this at this fails with a 422 error now? Is this the expected behavior?

`info: POST /api/v1/Users
warn: Validation error[422]: Username in use; Email in use.
info: POST /api/v1/Users 422 9ms`

If so would you like me to write some tests to cover this condition?

**Comment by mjs** [comment]
@jamie-sherriff So the issue is already fixed but there's no test coverage? If so, a test for this would great. Thanks!

**Comment by mjs** [comment]
Fixed!
